---
# Set a script 

- name: Install dependencies
  apt:
    name: '{{ motd_deb_script.dependencies }}'
    state: latest

- name: Set script in /etc/profile.d/
  template:
    src: '{{ motd_deb_script.template | default("default.j2") }}'
    dest: /etc/profile.d/{{ motd_deb_script.file | default( motd_deb_script.template | splitext | first | default( 'default' ) )}}.sh
    owner: root
    group: root
    mode: u=rwx,g=rx,o=rx

...
